name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x

      - name: Setup templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.924

      - name: Prepare assets
        run: make prepare

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Prober
        run: make client

      - name: Build Server
        run: make server
